### ISSUE TITLE
Prevent the "Hit enter" prompt

### ISSUE THREAD

**Issue by Shurakai** [beloglazov/vim-online-thesaurus#10]
Currently, echoing "Requesting thesaurus.com to look up the word ..." causes the "Hit Enter" prompt, which is absolutely annoying if you use this plugin a lot :) 

Hence, I propose to remove this line. I tried to print it using setline (:setline(1, '.....')) but it doesn't seem
to work with the immediate exec call after that. Dunno....

I think that the echo can be removed or at least a variable could be introduced to turn this off :-)

**Comment by beloglazov** [comment]
Closing as I can't reproduce the issue.
