### ISSUE TITLE
Words with multiple definitions?

### ISSUE THREAD

**Issue by tlnagy** [beloglazov/vim-online-thesaurus#11]
Would it be possible to list synonyms for all of the definitions of a word? Take the following as an example: <http://www.thesaurus.com/browse/approach>. This plugin only returns the synonyms for the first definition, not for the others. Many words can be used in different contexts, which changes the relevant synonyms. This would be a very nice feature to have.

Thanks!

**Comment by beloglazov** [comment]
Implemented in #15

**Comment by tlnagy** [comment]
Thanks! :+1:
