### ISSUE TITLE
"/bin/sort" workaround can fail

### ISSUE THREAD

**Issue by orodley** [beloglazov/vim-online-thesaurus#14]
In 780cd43, the invocation of `sort` was changed to `/bin/sort`, apparently to work around a conflict on Windows. However, `sort` is not always installed to this directory - for example, on Debian, it is in `/usr/bin/sort`. I changed it to get it working for me, but I'm not sure how to make it work in general.

I guess you could use `/bin/sort` only under Windows by checking `uname` and otherwise default to just `sort` to use whatever's in your `$PATH`?

**Comment by beloglazov** [comment]
Thanks for reporting! I haven't noticed this problem when testing on my system. I've replaced `/bin/sort` with `env sort` in 3e566c267f8eacb00cd5131f44801a708897ef02, this should solve the problem in Linux.

@blablatros could you please test the 3e566c267f8eacb00cd5131f44801a708897ef02 commit to see if it works in Windows? Thanks!

**Comment by blablatros** [comment]
No.

`env bin` evokes windows sort.

**Comment by beloglazov** [comment]
I see, how about b642b7f7983c8fe4d17c4b7615fd08aebd458ace?

**Comment by blablatros** [comment]
It works! Thanks!

**Comment by orodley** [comment]
Works for me too. Thanks very much!

**Comment by beloglazov** [comment]
Thanks for testing!
