### ISSUE TITLE
Specify `par` dependency

### ISSUE THREAD

**Issue by rafi** [beloglazov/vim-online-thesaurus#19]
The script wasn't able to collect data without first install `par`.

**Comment by av3r4ge** [comment]
Can you please tell what was exactly the problem without par and which OS and version of Vim you use?

I don't have par and it works well, so this should not be a problem.

**Comment by rafi** [comment]
My mistake. I'm on a Mac now and forgot I `set formatprg=par\ -w78` long time ago. Thanks!
