### ISSUE TITLE
windows support ?

### ISSUE THREAD

**Issue by muratkarakus7** [beloglazov/vim-online-thesaurus#24]
Is there any windows support for this plugin ?

**Comment by beloglazov** [comment]
Not at the moment, as it uses a shell script to fetch information (https://github.com/beloglazov/vim-online-thesaurus/blob/master/plugin/thesaurus-lookup.sh). I'm happy to accept a PR adding Windows support.

**Comment by muratkarakus7** [comment]
thanks, idea is good, I am planning to write a python script to support it.
