### ISSUE TITLE
How to get this plugin working with multiple words, like phrasal verbs?

### ISSUE THREAD

**Issue by gagallo7** [beloglazov/vim-online-thesaurus#30]
First of all, I'm very happy with this plugin.

But I was just wondering if there is support for phrasal verbs inputs like "get along with".
Since thesaurus has this feature: http://www.thesaurus.com/browse/get%20along%20with?s=t

**Comment by av3r4ge** [comment]
`:Thesaurus get along with`

**Comment by beloglazov** [comment]
At the moment, you could use what @av3r4ge suggested. But I think adding support for calling the plugin based on the visual mode selection shouldn't be too hard. I'm happy to accept pull requests :)

**Comment by beloglazov** [comment]
You could use what @av3r4ge suggested, or you could also add a visual mode mapping like the following, which requests a thesaurus entry for the selected text:

```
vnoremap <unique> <LocalLeader>K y:Thesaurus <C-r>"<CR>
```
