### ISSUE TITLE
Get rid of "Main entry:" line and instead include entry in the tab name

### ISSUE THREAD

**Issue by Granitas** [beloglazov/vim-online-thesaurus#32]
Would be great for people who are real estate starved. 2 lines is a lot in some cases :)
example (sorry for bad gimp skills):

![vim_thesaurus_enhancement](https://cloud.githubusercontent.com/assets/5476164/9430174/ec9c4be8-49f3-11e5-8314-ff7f18a21b8b.png)

**Comment by beloglazov** [comment]
I like the idea! Might take me a while to try this though :)

**Comment by beloglazov** [comment]
This is now implemented.
