### ISSUE TITLE
Replace searched word with thesaurus window selection?

### ISSUE THREAD

**Issue by isbadawi** [beloglazov/vim-online-thesaurus#33]
It would be cool if, after searching for the current word, I could choose a replacement in the thesaurus window, and have it replace the word I searched for in the original window. Doing this manually takes a few steps -- select, yank, close or switch window, and paste over the original word. It might even be faster to just type out the replacement.

I am thinking e.g. a buffer-local mapping in the thesaurus window to choose the (possibly multi-word) term under the cursor, carry out the replacement, and close the thesaurus window. Perhaps `<cr>` as a default, similar to running a command in the cmdline window.

I'm not facile enough with vimscript to know how simple that is to implement. I might give it a shot if I have time, but if this is easy then consider this a feature request.

**Comment by beloglazov** [comment]
Thanks for the suggestion! It sounds doable, but I don't really have time to work on this at the moment. I'd be happy to accept a PR :)

**Comment by Ron89** [comment]
I sort of did what he asked... but I basically altered it into a python based plugin, so I made it into a new plugin.
https://github.com/Ron89/thesaurus_query.vim

**Comment by beloglazov** [comment]
Thanks @Ron89! I think this issue can be closed now, and people who need this functionality can use your plugin.
